encyclopedia/urls.py
from django.urls import path
from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("not_found", views.not_found, name="not_found"),
    path("search", views.search, name="search"),
    path("new_page", views.new_page, name="new_page"),
    path("edit_page/<str:title>", views.edit_page, name="edit_page"),
    path("random_page", views.random_page, name="random_page"),
    

]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
import markdown2
from . import util
import re
from django import forms
import random
from django.core.files.base import ContentFile
from ast import *





def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form": NewSearch(),
    })

def entry(request, title):
    entry = util.get_entry(title)
    print(entry)

    if entry == None:
        return HttpResponseRedirect(reverse("encyclopedia:not_found"))
    else:
        content = markdown2.markdown(entry)
        return render(request, "encyclopedia/entry.html", {
        "content": content, "title": title,
        "form": NewSearch(),
        })


class NewSearch(forms.Form):
    search = forms.CharField(label='Search')

def search(request):
    if request.method == 'POST':
        form = NewSearch(request.POST)
        if form.is_valid():
            title = form.cleaned_data["search"]
            result = util.get_entry(title) 
            if result == None:
                suggestions = util.list_substring_entries(title)
                return render(request, "encyclopedia/suggestions.html", {
                            "suggestions": suggestions,
                            "search": title,
                            "form": NewSearch(),
                })
            else:
                return HttpResponseRedirect(reverse('encyclopedia:entry', args=({title})))  
    else:
        return HttpResponseRedirect(reverse("encyclopedia:not_found"))

def not_found(request):
    return render(request, "encyclopedia/not_found.html",{
        "form": NewSearch(),
        })

def random_page(request):
    numberPages = len(util.list_entries())
    indexPage = random.randrange(numberPages)
    page = util.list_entries()[indexPage]
    return HttpResponseRedirect(reverse('encyclopedia:entry', args=({page})))  



class NewPage(forms.Form):
    title =  forms.CharField(widget=forms.TextInput)
    content = forms.CharField(widget=forms.Textarea)

                  
def new_page(request):
    if request.method == 'POST':
        newpage = NewPage(request.POST)
        if newpage.is_valid():
            title = newpage.cleaned_data["title"]
            if util.get_entry(title) == None:
                content = newpage.cleaned_data["content"]
                util.save_entry(title, content)
                return HttpResponseRedirect(reverse('encyclopedia:entry', args=({title})))
            else:
                return render(request, "encyclopedia/new_page.html",{
                "newPage": NewPage(),
                "pagealreadyExisting": title,
                })

        else:
            return render(request, "encyclopedia/new_page.html",{
            "newPage": NewPage(),
            })
    else:        
        return render(request, "encyclopedia/new_page.html",{
            "newPage": NewPage(),

            })
    

class EditPage(forms.Form):
    content = forms.CharField(widget=forms.Textarea)

def edit_page(request, title):
    entry = util.get_entry(title)
    
    if request.method == 'POST':
        page = EditPage(request.POST)
        if page.is_valid():
            content = page.cleaned_data["content"]
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse('encyclopedia:entry', args=({title})))
        else:
            return HttpResponseRedirect(reverse('encyclopedia:edit_page', args=({title})))

    else:
        print(title)
        initial_dict = {
            "content": entry,
            }
        editPage = EditPage(initial = initial_dict)
       
        return render(request, "encyclopedia/edit_page.html", {
            'editContent': editPage,
            "title": title,
        })

encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - {{ title }} (Edit)
{% endblock %}

{% block body %}
    <h1>Edit page: {{ title }}</h1>

    <form action="{% url 'encyclopedia:edit_page' title=title %}" method="post">
        {% csrf_token %}
        {{ editContent }}
        <button type="submit">Save</button>
    </form> 

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
    Encyclopedia - {{ title }}
{% endblock %}

{% block body %}

    
    {{ content |safe }}

    <div class="edit"><a href="{% url 'encyclopedia:edit_page' title=title %}">Edit this page</a></div>

    

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - Index
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
        <li><a href="{% url 'encyclopedia:entry' title=entry %}">{{ entry }}</a></li>
        {% empty %}
            There are no entries yet  
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="wrapper">
            <div class="bar">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>

                </div>
                <div>
                    <a href="{% url 'encyclopedia:new_page' %}">Create New Page</a>
                </div>
                <div> 
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - New Page
{% endblock %}

{% block body %}

    {% if pagealreadyExisting %}
    <h2>Error: The page "{{ pagealreadyExisting }}" already exist</h2>
    {% endif %}

    <h1>Create a new page</h1>

    <form action="{% url 'encyclopedia:new_page' %}" method="post">
        {% csrf_token %}
        {{ newPage }}
        <button type="submit">Save</button>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/not_found.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
    Encyclopedia - Not Found
{% endblock %}

{% block body %}

    
         <h2>Requested page could not be found</h2>
   

{% endblock %}

encyclopedia/templates/encyclopedia/suggestions.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - No results
{% endblock %}

{% block body %}
    <h1>No results for: "{{ search }}" </h1>
    
        {%if suggestions%}
        <h3>You are maybe looking for:</h3>
        <ul>
        {% for suggestion in suggestions %}
        <li><a href="{% url 'encyclopedia:entry' title=suggestion %}">{{ suggestion }}</a></li> 
        {% endfor %}
        </ul>
        {% endif %}
    

{% endblock %}